In [2]:
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

import tensorflow as tf
from tensorflow import keras

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.head()

   customerID  gender  SeniorCitizen Partner  ...              PaymentMethod  MonthlyCharges TotalCharges Churn
0  7590-VHVEG  Female              0     Yes  ...           Electronic check           29.85        29.85    No
1  5575-GNVDE    Male              0      No  ...               Mailed check           56.95       1889.5    No
2  3668-QPYBK    Male              0      No  ...               Mailed check           53.85       108.15   Yes
3  7795-CFOCW    Male              0      No  ...  Bank transfer (automatic)           42.30      1840.75    No
4  9237-HQITU  Female              0      No  ...           Electronic check           70.70       151.65   Yes

[5 rows x 21 columns]